import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/ThemeProvider";
import Header from "@/components/Header"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";
import SearchPlace from "@/components/SearchPlace";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <Header />
      <Navbar />
      <SearchPlace />
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  );
}
